version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: orchestrator_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  orchestrator:
    build: .
    container_name: orchestrator_service
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "5005:5005"
    depends_on:
      - rabbitmq