version: '3.8'

services:
  db:
    image: postgres:16
    container_name: flight_postgres
    environment:
      POSTGRES_DB: flightdb
      POSTGRES_USER: flightuser
      POSTGRES_PASSWORD: flightpass
    ports:
      - "5434:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - flight-net

  flight-service:
    build: .
    container_name: flight_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/flightdb
      SPRING_DATASOURCE_USERNAME: flightuser
      SPRING_DATASOURCE_PASSWORD: flightpass
    ports:
      - "5003:5003"
    depends_on:
      - db
    networks:
      - flight-net

networks:
  flight-net:
    driver: bridge